services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/var/www/html
  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    command: php artisan queue:work redis --sleep=3 --tries=3
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
  db:
    image: 'mysql:8.4'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laracket
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - 'db-data:/var/lib/mysql'
  redis:
    image: 'redis:8.4-alpine'
    ports:
      - '6379:6379'
  meilisearch:
    image: 'getmeili/meilisearch:v1.12'
    ports:
      - '7700:7700'
    environment:
      MEILI_ENV: development
    volumes:
      - 'meilisearch-data:/meili_data'
  localstack:
    image: localstack/localstack:3.8
    ports:
      - '4566:4566'
    environment:
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - SERVICES=s3,ses
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - './docker/localstack:/etc/localstack/init/ready.d'

volumes:
  db-data:
  meilisearch-data:
